name: Format And Lint Code

on:
  pull_request:
    branches: [ "main-dev" ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
      issues: 'write'
      checks: 'write'

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      # Setup
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip and install flit
        run: |-
          python -m pip install --upgrade pip
          pip install flit
      - name: Install Dependencies
        run: |-
          flit install --deps=all --extras=all --symlink

      # Format Code
      - name: format
        run: ./scripts/format.sh

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
      issues: 'write'
      checks: 'write'

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      # Setup
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip and install flit
        run: |-
          python -m pip install --upgrade pip
          pip install flit
      - name: Install Dependencies
        run: |-
          flit install --deps=all --extras=all --symlink

      # Lint Code
      - name: lint
        run: ./scripts/lint.sh
